### PR TITLE
Improve EE10 compatibility

### LINKED ISSUE #345: EE10 Compatible Release
This is a follow up to #304 and related to IQSS/dataverse#8305

Trying to get this rolling with Jakarta EE 10 snapshots, I experienced the following problems:

- Module `rewrite-integration-cdi` uses a lot of CDI stuff that has been deprecated since CDI 1.1/2.0/3.0 and is now removed in 4.0. (FWIW [CDI 3.0 Spec HTML](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html))
- Module `rewrite-integration-faces` uses `@ManagedBean` detection, which has been [removed from Faces 4.0](https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html#ManagedBean)
- Module `config-prettyfaces` uses [JSP support for JSF which has been removed](https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html#JSP) (No more `jakarta.faces.webapp.UIComponentELTag`)
- ...

### PR DESCRIPTION
**Pull request by poikilotherm**
- Add integration testing with Payara in addition to Wildfly
- Fix tests for EE10 (CDI and Faces changes)
- If missing code changes discovered via testing, add here, too

Closes #345 

Discoveries so far:
- Tests using CDI or Faces need proper configuration of CDI via `beans.xml`. Discovery mode seems to be necessary to be set to `all`, which is different than the default `annotated`! [See spec](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#_jakarta_contexts_and_dependency_injection_4_0) This means that any app using this lib via CDI or Jakarta Faces will need to enable this discovery mode, too! (This should be documented and maybe fixed at a later point in time.)

TODOs:
- [x] Refactor Jakarta Faces using tests, adapting to changed specs.
- [ ] Add docs

### CODE REVIEW

**Comment by lincolnthree** [comment]
Hey @poikilotherm - Thanks for the PR & update!

Thanks for the `beans.xml` fix, too.

I did a quick review, and it looks like you've introduced a new EE10 profile. Can you tell me how this is intended to be used? I assume it needs to be specified along side (together with) one of the other managed profiles?

Additionally, it looks like some tests are now failing on Wildfly, but I'm not sure why anything would be different. All you did was bump a version for that profile, right?

**Comment by poikilotherm** [comment]
Hey @lincolnthree , basically the first PR was never all set and done with EE10 as it was still using Wildfly 26 and EE9.1. Most of the patches were left stashed in my local branch. 

The new profile was because of trying to not create another feature branch for EE10 which would need extra maintenance. I had hoped to create a profile might be enough to get us going and maybe release Jars like Primefaces does it for EE8 and Jakarta-based.

Now that the branch is a reality we might just skip that.

The tests fail because of the CDI and Faces changes in EE10, see TODOs above.
This is a WIP and I should have created a draft PR.

**Comment by lincolnthree** [comment]
Gotcha! That makes sense. Thanks for the extra info :) I appreciate your efforts on this! Let me know if there's anything I can do to support you with the CI or GitHub infrastructure.

**Comment by poikilotherm** [comment]
@lincolnthree I managed to get all tests running on *both* Payara + Wildfly *plus* Jakarta EE 9.1 and 10.

Please note that @larsgrefer did change some modules to ignore outcomes of ITs in `config-prettyfaces-tests`, `integration-faces-tests` and `security-integration-shiro`. I did not address any of those here, leaving it as an exercise for later.

As the codebase now *should* work with both EE9 and EE10 - should we think about releasing JARs to central from one branch for both "versions"? (They only differ in dependencies.)

**Comment by poikilotherm** [comment]
Alright @lincolnthree:

- Moved this to be Jakarta EE 10 by default in this Maven build.
- Increased the major version number to be 6.0 to avoid conflicts with the EE 9.1 build
- Some more cleanup of properties and especially updating Maven plugins

Question for you: should we setup a deployment pipeline for snapshots and releases? I've done this before for https://github.com/gdcc/xoai and https://github.com/gdcc/sword2-server, so can inherit from there.

Another question for you: what kind of docs do you want me to include? Should I update the README, add build status, EE version with badges, etc? Should this even be a part of this PR or for a next round?

**Comment by lincolnthree** [comment]
Hey @poikilotherm, thank you for the continued work! I think the first thing we should do is publish an Alpha build in central and get some real-world results.

A deployment pipeline for releases would be awesome, but unfortunately I don't have a lot of free time to set that up at the moment.  I wish I had time to look at why the ITs are failing on certain containers as well, but alas...

Anyway, I believe snapshots should be auto-published already via the existing GitHub workflows?
* https://github.com/ocpsoft/rewrite/blob/main/.github/workflows/maven-deploy.yml
* https://repository.sonatype.org/#nexus-search;gav~org.ocpsoft.rewrite~rewrite-servlet~~~~kw,versionexpand

Let's do the work of getting a consumable JAR/distribution build published first, then we can get the docs updated in a subsequent PR.

**Comment by lincolnthree** [comment]
I'm not sure how long snapshots stay in this repo. It looks like they have rolled off already:
[sonatype-nexus-snapshots](https://s01.oss.sonatype.org/content/repositories/snapshots/org/)

**Comment by lincolnthree** [comment]
@larsgrefer Do you happen to know how long SNAPSHOT builds stay published on sonatype? Or am I looking at the wrong repo?

**Pull request merged**
