### PR TITLE
Change log level

### PR DESCRIPTION
**Pull request by rafaelstelles**

### CODE REVIEW

**Comment by rafaelstelles** [comment]
Hi everyone,

      I migrated to production and I noticed that this log it should "FINE", correct ?

**Comment by lincolnthree** [comment]
Hey Rafael, that's right. Good catch! I'll get this fixed.

**Comment by rafaelstelles** [comment]
Hi @lincolnthree ,

   When you imagine publish new version ?

Thanks

**Comment by lincolnthree** [comment]
It should be in Maven central already! Let me know if you still don't see it.

**Comment by rafaelstelles** [comment]
@lincolnthree , I saw now. Thanks.

**Comment by lincolnthree** [comment]
You're welcome! Thanks again for finding the issue :)

**Pull request merged**
