### PR TITLE
Fix #243: Prevent NullPointerExceptions

### LINKED ISSUE #243: NullPointerException in org.ocpsoft.urlbuilder.AddressBuilder#queryDecoded
Method throws NullPointerException with given input (line 204)
CharSequence name = null
Object... values = Object[0]

Method called from org.ocpsoft.rewrite.servlet.config.PathAndQuery#evaluateHttp (line 133)

InboundRewrite [POST url=http://localhost:8080/rest/authenticationServices/validateUserCredentials, flow=UN_HANDLED, dispatchResource=null]

```
    <dependency>
        <groupId>org.ocpsoft.rewrite</groupId>
        <artifactId>rewrite-servlet</artifactId>
        <version>3.4.1.Final</version>
    </dependency>
    <dependency>
        <groupId>org.ocpsoft.rewrite</groupId>
        <artifactId>rewrite-integration-cdi</artifactId>
        <version>3.4.1.Final</version>
    </dependency>
```

### PR DESCRIPTION
**Pull request by rumdidumdum**
Proposal to fix #243.

### CODE REVIEW

**Comment by chkal** [comment]
Hey @rumdidumdum. Thanks a lot for the PR. I'm currently traveling, so it may take some time for me to do the review. Sorry about that. I'll come back to you ASAP.

**Comment by chkal** [comment]
Hey @rumdidumdum. Thanks a lot for the pull request. I just reviewed it and it looks fine. And it will definitely work around the NPEs you got.

However, I'm not sure if this really addresses the root cause of the underlying problem. Actually in my opinion the problem is caused by this line:

https://github.com/ocpsoft/rewrite/blob/f79e31b250866eefc983ac2b20018255b6ed7c95/config-servlet/src/main/java/org/ocpsoft/rewrite/servlet/config/PathAndQuery.java#L134

Instead of using `queryDecoded()`, the code should call `queryLiteral()`. That's because `event.getInboundAddress().getQuery()` actually returns a full query string like `foo=bar&a=1&b=3`. So calling `queryDecoded()` makes no sense here. If there is no query string, the code will pass `null` into `queryDecoded()` leading to the problem you ran into. If we would call `queryLiteral()` instead, the `null` value is handled correctly.

What do you think?

**Comment by rumdidumdum** [comment]
Hi @chkal. Thanks for your feedback. I didn't know about the `queryLiteral()` method, but I think you're right in that invoking this method instead of `queryDecoded()` will actually fix the root cause of our NPEs. I will update my pull request accordingly.

**Comment by chkal** [comment]
Awesome! It would be great if you could test if this really fixes you problem so we can include it in the next release.

**Comment by rumdidumdum** [comment]
Hi @chkal. Your suggestion to use `queryLiteral()` instead `queryDecoded()` does indeed fix the root cause of the NPE in `PathAndQuery`.

The fix also works without the previously introduced `null` checks in `AddressBuilder`. I still left them for improved code stability. What do you think?

**Comment by chkal** [comment]
Awesome! Thanks a lot for your help to fix this. I also think that the null checks are great. So lets keep them. Merged! :beers:

**Pull request merged**
