### PR TITLE
#201 - solves concurrency issue w/ double checked locking

### PR DESCRIPTION
**Pull request by nordstrand**

### CODE REVIEW

**Comment by nordstrand** [comment]
Fixes #201

**Comment by chkal** [comment]
That's awesome. Thank you so much. :)

One question. Why do you use the local variable `result`. Why not just work on the field `dispatcherTypeProviders` directly? Is there any reason for this? If not, could you perhaps remove it? The current code is a bit hard to read this way.

Thanks a lot! We are always very happy to see contributions!

**Comment by nordstrand** [comment]
According to [the Wikipedia article on double checked locking](http://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java) the introduction of the local makes the code more performant in the general case, even thought I agree it's more convoluted.

**Comment by chkal** [comment]
Ah, OK. I wasn't aware that this is a pattern to improve performance. Looks like I just learned something new. ;)

I'll merge the patch. Thanks a lot for your help with this.

**Pull request merged**
