### PR TITLE
Update maven versions

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by lincolnthree** [comment]
Thank you @larsgrefer -- I think we should probably update the major version with this branch. It certainly won't be backwards compatible :)

**Comment by lincolnthree** [comment]
Would you like me to merge this? I see a lot of commits but

**Comment by larsgrefer** [comment]
@lincolnthree I think we should to the upgrades in two steps, thereby creating two new Versions of Rewrite:

1. All the cleanups and improvements so far, but still with a Jakarta EE 8 baseline (still `javax.*` packages)
2. A further updated version with Jakarta EE 9 baseline.

The question is, if these versions should be `3.6.x` and `4.x` or even `4.x` and `5.x`

**Comment by larsgrefer** [comment]
> Is Jakarta EE 9 when the switch to jakarta.* was made?

Exactly. The Jakarta EE 8 API's are identical to Java EE 8.

**Pull request merged**
