### PR TITLE
Migrate `main` from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by larsgrefer**
One to one migration from travis to github actions in order to compare the failing tests on develop with the tests on main

### CODE REVIEW

**Comment by larsgrefer** [comment]
@lincolnthree This should be ready to merge now.

I'm not sure what to do with the remaining entries in `.travis.yml`. Apart from that, the CI and Snapshot-Publishing should now be completely migrated to GitHub Actions for the main branch.

After this has been merged into main, I will try to forward-merge main, into develop and develop-jakartaee-9.

**Comment by lincolnthree** [comment]
This looks great @larsgrefer - For the travis stuff, I'd say just get rid of it as Github Actions is essentially replacing this. That notifications email address is defunct now anyway, so I'd say it's safe to remove and rely on the Github notification infrastructure. It's a better integration anyway. 

If you agree, do you mind removing that from the PR entirely? Then I'll go ahead and merge!

**Comment by larsgrefer** [comment]
@lincolnthree Done.

One thing is left to do for you: Environment variables that where defined for travis-ci (namely `SONATYPE_USERNAME` and `SONATYPE_PASSWORD`) must now be declared as Github Secrets: https://github.com/ocpsoft/rewrite/settings/secrets/actions or https://github.com/organizations/ocpsoft/settings/secrets/actions

**Comment by lincolnthree** [comment]
Okay @larsgrefer I've added the secrets, and merged this. Let's see how it goes! THANK YOU :D

**Pull request merged**
