### PR TITLE
Remove collection casts

### PR DESCRIPTION
**Pull request by mdfst13**
Since Java doesn't like casting Collection to Collection<Type>, move the casts to the individual objects.  This simply reduces compiler noise.  I.e. my IDE was producing warnings but stopped after this change.  

Includes merge/rebase commits that could be squashed.  Only the final commit matters.

### CODE REVIEW

**Comment by mdfst13** [comment]
Interestingly, this looks like another case where the tests run locally but have trouble with Travis.  It's unclear to me why these changes would affect Wildfly but not JBoss AS, Glassfish, or Tomcat.  

It is unlikely that I will do further debugging.

**Comment by chkal** [comment]
I restarted the Travis build. Let's see if this was just a random failure. The broken test was related to concurrency testing and I remember that this tests has also failed randomly in the past.

Regarding your change: To be honest, I don't understand why your IDE is complaining. Could you post details about the error. You are getting the warning in this line?

```java
ServiceLoader<ConfigurationProvider> configLoader = ServiceLoader.load(ConfigurationProvider.class);
```

That shouldn't be a problem. That's how the `ServiceLoader` API should be used. And I don't think that changing the generic type to `<?>` is a good thing to do. Could you share details about the warning?

**Comment by mdfst13** [comment]
> Type safety: The expression of type ServiceLoader needs unchecked conversion to conform to ServiceLoader<ConfigurationProvider>
> 
Type safety: The expression of type ServiceLoader needs unchecked conversion to conform to ServiceLoader<ConfigurationPostProcessor>
> 
Type safety: The expression of type ServiceLoader needs unchecked conversion to conform to ServiceLoader<DevelopmentModeDetector>

On `ServiceLoader.load` in each case.

**Comment by chkal** [comment]
Ah, I see. I was just checking this myself. And it looks like this isn't actually the JDK's `ServiceLoader` class, but a custom one from the `ocpsoft-commons` package.

It looks like the `load()` method in this custom implementation returns `ServiceLoader` and not `ServiceLoader<T>`. So that's causing these issues. But it looks like there is a `loadTypesafe()` method which is defined just like the JDK's `load()` method. So replacing `load()` with `loadTypesafe()` would be a much cleaner fix. Could you give it a try?

**Comment by mdfst13** [comment]
Yes, that also gets rid of the warning.  And passes Travis.

**Comment by chkal** [comment]
Great! Thanks!

**Pull request merged**
