### PR TITLE
Wrap original exception to preserve complete stack trace

### PR DESCRIPTION
**Pull request by romixch**
Hi everybody

I ran into a problem with rewriting an url and could not analyze the original problem because this code throws away part of the stack trace. This commit should fix it.

Thank you for your work!
Roman

### CODE REVIEW

**Comment by chkal** [comment]
Awesome! Thanks a lot! Looks good to me!

Actually I'm wondering why we need these `catch(Exception e)` blocks at all. I would actually think it would be nice to get rid of them. Especially because they don't just catch rewrite exceptions, but all other application exceptions too (as Rewrite is a Servlet filter). @lincolnthree: What do you think?

However, you patch is a good first step!!!

**Comment by romixch** [comment]
Actually the message in the wrapper exception with a mention of event and rule helped me a lot solving my configuration problem. Don't know if the message of the original exception was more helpful. Maybe.

**Comment by chkal** [comment]
In my case most runtime exceptions basically were thrown though the full Servlet filter chain and then were catched by Rewrite. No other Servlet filter does this. So I wonder if Rewrite should really do that.

**Comment by lincolnthree** [comment]
Sorry for my late attendance to this discussion. I've had it open in my browser since you mentioned it. I think this is the right solution, but we probably want to make our exception wrapping a little smarter. E.g. Only wrap exceptions if they were originally thrown by rewrite, but instead log DEBUG messages if to include relevant information if they are not.

**Comment by lincolnthree** [comment]
This is the right fix for now. Thanks for taking care of it :)

**Pull request merged**
