### PR TITLE
Add Jakarta EE 10 compatibility

### LINKED ISSUE #345: EE10 Compatible Release
This is a follow up to #304 and related to IQSS/dataverse#8305

Trying to get this rolling with Jakarta EE 10 snapshots, I experienced the following problems:

- Module `rewrite-integration-cdi` uses a lot of CDI stuff that has been deprecated since CDI 1.1/2.0/3.0 and is now removed in 4.0. (FWIW [CDI 3.0 Spec HTML](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html))
- Module `rewrite-integration-faces` uses `@ManagedBean` detection, which has been [removed from Faces 4.0](https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html#ManagedBean)
- Module `config-prettyfaces` uses [JSP support for JSF which has been removed](https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html#JSP) (No more `jakarta.faces.webapp.UIComponentELTag`)
- ...

### LINKED ISSUE #346: Cannot build branch `develop-jakartaee-9` with JDK 11
Thanks everyone involved with #304 

While trying to update to EE 10 I noticed I could not fully build the packages using Java 11 LTS only. Looks like this slipped through because of the Github Action using JDK 17 and 18 only.

Maven Enforcer also forbids `rewrite-integration-spring` to be executed with JDK 11.

It fails at `rewrite-config-prettyfaces`:

```
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ rewrite-config-prettyfaces ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.ocpsoft.pretty.faces.beans.ActionExecutorTest
[ERROR] Tests run: 8, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.083 s <<< FAILURE! - in com.ocpsoft.pretty.faces.beans.ActionExecutorTest
[ERROR] testShouldExecuteOnNonPostback(com.ocpsoft.pretty.faces.beans.ActionExecutorTest)  Time elapsed: 0.022 s  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/apache/commons/logging/LogFactoryService has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at com.ocpsoft.pretty.faces.beans.ActionExecutorTest.<init>(ActionExecutorTest.java:30)
```

On a related note I see that the release to Maven Central is also done using Java 17. I'm not sure this will retain compatibility with JDK 11 using projects. Jakarta EE 10 requires JDK 11 minimum.

### PR DESCRIPTION
**Pull request by poikilotherm**
Closes #345
Closes #346 

This isn't ready yet, as I want to change the Github Action to build with both Jakarta EE 9 and EE 10, so down the road we can make sure it builds and runs with both.

This also means adding Wildfly 27 into the mix, which is their first EE 10 based release. [Currently in Alpha](https://github.com/wildfly/wildfly/releases/tag/27.0.0.Alpha3), but nearing the finish line just as Payara.

If you folks feel we should add a Payara 6 testing flavor, too, please speak out.

If you want me to split up the PR in multiple smaller ones, please let me know.

### CODE REVIEW

**Comment by poikilotherm** [comment]
Hey @larsgrefer @lincolnthree maybe you can take a first look at this?

**Comment by lincolnthree** [comment]
Hey guys. First, my apologies for keeping you all waiting for so long after putting in so much work on this. This summer has been incredibly challenging for personal reasons, so I just want to say thank you for your patience and I'm sorry again. I'm back in the saddle for a bit and will get the workflow (and hopefully discussion) started back up again on this.

**Comment by lincolnthree** [comment]
@poikilotherm One question. It looks like you are currently basing this on the jakarta-ee-9 branch. Is Jakarta EE 10 backwards compatible with 9? Should this have its own branch?

Also currently trying to figure out why actions are not available on this PR. Working on it...

**Comment by lincolnthree** [comment]
Don't worry when you see this @poikilotherm I'm closing this temporarily to try opening a new PR and see if that gets actions working.

**Comment by lincolnthree** [comment]
Ok simply closing and re-opening did the trick. Strange.

**Comment by lincolnthree** [comment]
@poikilotherm @larsgrefer Given that this removes support for JSP, which is still compatible with EE 9, I'm inclined to base this on a new `develop-jakartaee-10` branch. Thoughts?

**Comment by codylerum** [comment]
I'm approaching in the midst of my upgrade to EE10 and (Wildfly 27) and I'm wondering where we stand on this?

**Comment by lincolnthree** [comment]
Hey @codylerum . As far as I know, this needs a new branch, and some snapshots. Would that help in your testing?

**Comment by lincolnthree** [comment]
@poikilotherm @codylerum 6.0.0.Alpha1 (which should support EE10 via this PR) should be in maven central soon. Just did the release.

**Comment by codylerum** [comment]
@lincolnthree Thanks I'm hoping to take it for a spin in the next week or so

**Pull request merged**
