### PR TITLE
Prevented adding the same binding multiple times.

### PR DESCRIPTION
**Pull request by didiez**
fixes gh-223

### CODE REVIEW

**Comment by lincolnthree** [comment]
@didiez Hey! Thanks so much for this PR, and for analyzing and fixing the issue with double bindings.

One favor to ask. Could you please add a test that reproduces the issue, and verifies that this patch fixes it? We'd like to keep our test coverage high, particularly for granular/specific issues like this where chances of a regression error are high.

Thanks. Looking forward to hearing from you.

**Comment by didiez** [comment]
Done! Hope this helps
Thanks @lincolnthree

**Review by melloware — APPROVED** [review]

**Comment by lincolnthree** [comment]
Fantastic! Thanks @didiez - I'll review and merge ASAP if everything checks out.

**Comment by lincolnthree** [comment]
Released 3.5.0.Final -- Will be in central soon. Thanks again! And thanks for your patience.

**Pull request merged**
